// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/17/2024, 1:24:38 PM
const configMerger = require("/Users/xiangjianfeng/Github/diqiao/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/xiangjianfeng/Github/diqiao/components/**/*.{vue,js,mjs}","/Users/xiangjianfeng/Github/diqiao/layouts/**/*.{vue,js,mjs}","/Users/xiangjianfeng/Github/diqiao/pages/**/*.{vue,js,mjs}","/Users/xiangjianfeng/Github/diqiao/composables/**/*.{js,ts,mjs}","/Users/xiangjianfeng/Github/diqiao/utils/**/*.{js,ts,mjs}","/Users/xiangjianfeng/Github/diqiao/{A,a}pp.{vue,js,mjs}","/Users/xiangjianfeng/Github/diqiao/{E,e}rror.{vue,js,mjs}","/Users/xiangjianfeng/Github/diqiao/app.config.{js,ts,mjs}"] }));

module.exports = config
